import NavBar from "./components/header/header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const dynamic = 'force-dynamic';
// export const revalidate = 0;

export const metadata = {
  title: "修理伝票",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${inter.className} h-[calc(100vh-50px)] bg-gray-100`}>
        {children}
      </body>
    </html>
  );
}
