import NavBar from "./components/header/nav-bar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const dynamic = 'force-dynamic';
// export const revalidate = 0;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${inter.className} h-[calc(100vh-50px)] bg-gray-100`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
